baseURL = "https://hjbello.com"
title = "Hugo J. Bello"
theme = "ananke"

enableEmoji = true


MetaDataFormat = "yaml"
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number

googleAnalytics = "UA-181757842-1"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCTEk2zVUgVoio1DXtvFJtEg"
  github = "https://github.com/HugoJBello"
  linkedin = "https://es.linkedin.com/in/hugo-j-bello-5b4650120"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/frentes.jpg"
  recent_posts_number = 2

[languages]
  [languages.en]
    title = "Hugo J. Bello page"
    languageName = "English"
    weight = 1
    
  [languages.es]
    title = "Hugo J. Bello"
    languageName = "Spanish"
    weight = 2
     

